// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: users.proto

package example_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_GetUser_FullMethodName = "/user.UserService/GetUser"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUser(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

const (
	TestBoardService_Connect_FullMethodName   = "/user.TestBoardService/Connect"
	TestBoardService_PrintName_FullMethodName = "/user.TestBoardService/PrintName"
)

// TestBoardServiceClient is the client API for TestBoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestBoardServiceClient interface {
	// Establishes a connection that remains open for sending messages
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (TestBoardService_ConnectClient, error)
	PrintName(ctx context.Context, in *PrintNameRequest, opts ...grpc.CallOption) (*PrintNameResponse, error)
}

type testBoardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestBoardServiceClient(cc grpc.ClientConnInterface) TestBoardServiceClient {
	return &testBoardServiceClient{cc}
}

func (c *testBoardServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (TestBoardService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestBoardService_ServiceDesc.Streams[0], TestBoardService_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &testBoardServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestBoardService_ConnectClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type testBoardServiceConnectClient struct {
	grpc.ClientStream
}

func (x *testBoardServiceConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testBoardServiceClient) PrintName(ctx context.Context, in *PrintNameRequest, opts ...grpc.CallOption) (*PrintNameResponse, error) {
	out := new(PrintNameResponse)
	err := c.cc.Invoke(ctx, TestBoardService_PrintName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestBoardServiceServer is the server API for TestBoardService service.
// All implementations must embed UnimplementedTestBoardServiceServer
// for forward compatibility
type TestBoardServiceServer interface {
	// Establishes a connection that remains open for sending messages
	Connect(*ConnectRequest, TestBoardService_ConnectServer) error
	PrintName(context.Context, *PrintNameRequest) (*PrintNameResponse, error)
	mustEmbedUnimplementedTestBoardServiceServer()
}

// UnimplementedTestBoardServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestBoardServiceServer struct {
}

func (UnimplementedTestBoardServiceServer) Connect(*ConnectRequest, TestBoardService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedTestBoardServiceServer) PrintName(context.Context, *PrintNameRequest) (*PrintNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintName not implemented")
}
func (UnimplementedTestBoardServiceServer) mustEmbedUnimplementedTestBoardServiceServer() {}

// UnsafeTestBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestBoardServiceServer will
// result in compilation errors.
type UnsafeTestBoardServiceServer interface {
	mustEmbedUnimplementedTestBoardServiceServer()
}

func RegisterTestBoardServiceServer(s grpc.ServiceRegistrar, srv TestBoardServiceServer) {
	s.RegisterService(&TestBoardService_ServiceDesc, srv)
}

func _TestBoardService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestBoardServiceServer).Connect(m, &testBoardServiceConnectServer{stream})
}

type TestBoardService_ConnectServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type testBoardServiceConnectServer struct {
	grpc.ServerStream
}

func (x *testBoardServiceConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _TestBoardService_PrintName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestBoardServiceServer).PrintName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestBoardService_PrintName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestBoardServiceServer).PrintName(ctx, req.(*PrintNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestBoardService_ServiceDesc is the grpc.ServiceDesc for TestBoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestBoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.TestBoardService",
	HandlerType: (*TestBoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrintName",
			Handler:    _TestBoardService_PrintName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _TestBoardService_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "users.proto",
}
