// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package example_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type ConnectRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PrintNameRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintNameRequest) Reset()         { *m = PrintNameRequest{} }
func (m *PrintNameRequest) String() string { return proto.CompactTextString(m) }
func (*PrintNameRequest) ProtoMessage()    {}
func (*PrintNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *PrintNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintNameRequest.Unmarshal(m, b)
}
func (m *PrintNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintNameRequest.Marshal(b, m, deterministic)
}
func (m *PrintNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintNameRequest.Merge(m, src)
}
func (m *PrintNameRequest) XXX_Size() int {
	return xxx_messageInfo_PrintNameRequest.Size(m)
}
func (m *PrintNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrintNameRequest proto.InternalMessageInfo

func (m *PrintNameRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type PrintNameResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintNameResponse) Reset()         { *m = PrintNameResponse{} }
func (m *PrintNameResponse) String() string { return proto.CompactTextString(m) }
func (*PrintNameResponse) ProtoMessage()    {}
func (*PrintNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *PrintNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintNameResponse.Unmarshal(m, b)
}
func (m *PrintNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintNameResponse.Marshal(b, m, deterministic)
}
func (m *PrintNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintNameResponse.Merge(m, src)
}
func (m *PrintNameResponse) XXX_Size() int {
	return xxx_messageInfo_PrintNameResponse.Size(m)
}
func (m *PrintNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrintNameResponse proto.InternalMessageInfo

func (m *PrintNameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*ConnectRequest)(nil), "user.ConnectRequest")
	proto.RegisterType((*Message)(nil), "user.Message")
	proto.RegisterType((*PrintNameRequest)(nil), "user.PrintNameRequest")
	proto.RegisterType((*PrintNameResponse)(nil), "user.PrintNameResponse")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x14, 0x5c, 0x97, 0xb4, 0xa5, 0xaf, 0xb0, 0xda, 0xb5, 0x56, 0x4b, 0x14, 0x69, 0xd1, 0x2a, 0x20,
	0xd4, 0x03, 0x4d, 0x21, 0x5c, 0xe0, 0x82, 0xd4, 0x72, 0x40, 0x1c, 0x40, 0x28, 0xc0, 0x05, 0x21,
	0x21, 0x37, 0x7e, 0x2a, 0x11, 0x4d, 0x1c, 0xec, 0x97, 0xaa, 0xfc, 0x00, 0x9f, 0xc0, 0xf7, 0xa2,
	0xd8, 0x4e, 0x49, 0xe1, 0xb2, 0xa7, 0xf8, 0xcd, 0x4c, 0xc6, 0x33, 0x2f, 0x81, 0x69, 0x63, 0x50,
	0x9b, 0xa4, 0xd6, 0x8a, 0x14, 0x0f, 0xda, 0x21, 0xfe, 0xcd, 0x20, 0xf8, 0x64, 0x50, 0xf3, 0x53,
	0x18, 0x14, 0x32, 0x64, 0xd7, 0x6c, 0x16, 0x64, 0x83, 0x42, 0xf2, 0x2b, 0x80, 0x5c, 0xa3, 0x20,
	0x94, 0x5f, 0x05, 0x85, 0x83, 0x6b, 0x36, 0x9b, 0x64, 0x13, 0x8f, 0x2c, 0xa9, 0xa5, 0x9b, 0x5a,
	0x76, 0xf4, 0x2d, 0x47, 0x7b, 0x64, 0x49, 0x9c, 0x43, 0x50, 0x89, 0x12, 0xc3, 0xc0, 0x12, 0xf6,
	0xcc, 0x2f, 0x61, 0x24, 0x76, 0x82, 0x84, 0x0e, 0x87, 0x16, 0xf5, 0x13, 0xbf, 0x80, 0x21, 0xa9,
	0xef, 0x58, 0x85, 0x23, 0x0b, 0xbb, 0x21, 0x7e, 0x00, 0xd3, 0x36, 0x57, 0x86, 0x3f, 0x1a, 0x34,
	0xf4, 0x57, 0xc4, 0xfa, 0xa2, 0x2f, 0x70, 0xc7, 0x89, 0x4c, 0xad, 0x2a, 0x83, 0xed, 0xb5, 0xb9,
	0x92, 0x68, 0x45, 0xc3, 0xcc, 0x9e, 0x79, 0x08, 0xe3, 0x12, 0x8d, 0x11, 0x1b, 0xf4, 0x2d, 0xba,
	0x91, 0xdf, 0x87, 0x40, 0x0a, 0x12, 0x36, 0xfd, 0x34, 0x85, 0xa4, 0x5d, 0x48, 0x62, 0xfd, 0x2c,
	0x1e, 0x3f, 0x86, 0xd3, 0x57, 0xaa, 0xaa, 0x30, 0xa7, 0x2e, 0x45, 0x04, 0xb7, 0xf3, 0x6d, 0x81,
	0x15, 0xbd, 0x91, 0x3e, 0xc8, 0x61, 0x8e, 0xaf, 0x60, 0xfc, 0xd6, 0x1b, 0x73, 0x08, 0x08, 0xf7,
	0xe4, 0x25, 0xf6, 0x1c, 0x27, 0x70, 0xf6, 0x5e, 0x17, 0x15, 0xbd, 0x13, 0x25, 0xde, 0xc4, 0x6e,
	0x0e, 0xe7, 0x3d, 0xbd, 0xef, 0xd7, 0xeb, 0xc2, 0x8e, 0xba, 0xa4, 0x4b, 0xb7, 0xae, 0x0f, 0xa8,
	0x77, 0x45, 0x8e, 0x3c, 0x85, 0xf1, 0x6b, 0x24, 0xfb, 0x61, 0xcf, 0x7b, 0xbd, 0xdc, 0xbd, 0x11,
	0xef, 0x43, 0xce, 0x3a, 0x3e, 0x49, 0x7f, 0x31, 0x38, 0xfb, 0x88, 0x86, 0x56, 0x4a, 0x68, 0xd9,
	0x33, 0xf2, 0x3b, 0xe0, 0x17, 0xee, 0xad, 0xe3, 0x95, 0x44, 0x77, 0x1d, 0xea, 0xab, 0xc7, 0x27,
	0x4f, 0x18, 0x7f, 0x09, 0x93, 0x43, 0x74, 0x7e, 0xe9, 0xf8, 0x7f, 0xbb, 0x47, 0xf7, 0xfe, 0xc3,
	0xbb, 0x20, 0xab, 0x47, 0x9f, 0x1f, 0x6e, 0x0a, 0xfa, 0xd6, 0xac, 0x93, 0x5c, 0x95, 0x0b, 0xa9,
	0x76, 0x3f, 0xa5, 0x30, 0x4f, 0x5f, 0xa4, 0xcf, 0x17, 0xb8, 0x17, 0x65, 0xbd, 0xc5, 0xb9, 0xfd,
	0x83, 0xd7, 0x23, 0xfb, 0x78, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x9b, 0x6c, 0x8a, 0xd7,
	0x02, 0x00, 0x00,
}
